import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';import {fileURLToPath} from 'node:url';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StdioClientTransport} from '@modelcontextprotocol/sdk/client/stdio.js';
import {StreamableHTTPClientTransport} from '@modelcontextprotocol/sdk/client/streamableHttp.js';
import {createMcpHttpHandler} from '../lib/mcp.mjs';
const sample={mode:'sample',people:[['jazz','cinema'],['books','soul']],budget:140,vibe:'intimate',location:'New York City',startTime:'18:00'};
const parse=r=>r.structuredContent??JSON.parse(r.content[0].text);
async function stdio(){const client=new Client({name:'afterglow-protocol-test',version:'1.0.0'});const transport=new StdioClientTransport({command:process.execPath,args:[fileURLToPath(new URL('../mcp-server.mjs',import.meta.url))],env:{PATH:process.env.PATH,QLOO_ENABLED:'false'},stderr:'pipe'});await client.connect(transport);return client;}
test('real stdio handshake advertises usable tools and no bundled LLM',async()=>{const c=await stdio();try{const tools=await c.listTools();assert.deepEqual(tools.tools.map(t=>t.name).sort(),['afterglow_plan_evening','afterglow_sample_tastes','afterglow_search_favorites','afterglow_status']);for(const t of tools.tools)assert.equal(t.annotations.readOnlyHint,true);const status=parse(await c.callTool({name:'afterglow_status',arguments:{}}));assert.equal(status.inAppLlm,false);assert.equal(status.enabled,false);assert.ok(!JSON.stringify(status).includes('API_KEY'));}finally{await c.close();}});
test('external client can discover signals, plan and replan over MCP',async()=>{const c=await stdio();try{const catalog=parse(await c.callTool({name:'afterglow_sample_tastes',arguments:{}}));assert.equal(catalog.mode,'sample');assert.ok(catalog.tastes.some(t=>t.id==='jazz'));const a=parse(await c.callTool({name:'afterglow_plan_evening',arguments:sample}));assert.equal(a.mode,'sample');assert.equal(a.stops.length,3);assert.ok(a.cost<=140);const b=parse(await c.callTool({name:'afterglow_plan_evening',arguments:{...sample,budget:50}}));assert.ok(b.cost<=50);assert.match(b.warnings.join(' '),/fictional/);}finally{await c.close();}});
test('MCP rejects bad schema, disallows booking tools, and exposes live configuration errors',async()=>{const c=await stdio();try{const bad=await c.callTool({name:'afterglow_plan_evening',arguments:{...sample,budget:1}});assert.equal(bad.isError,true);const noBooking=await c.callTool({name:'book_restaurant',arguments:{}});assert.equal(noBooking.isError,true);const unavailable=await c.callTool({name:'afterglow_search_favorites',arguments:{query:'Nina Simone',type:'artist'}});assert.equal(unavailable.isError,true);assert.equal(parse(unavailable).code,'QLOO_NOT_CONFIGURED');}finally{await c.close();}});
test('MCP agent workflow prompt preserves provenance and user control',async()=>{const c=await stdio();try{const prompts=await c.listPrompts();assert.equal(prompts.prompts[0].name,'plan_an_afterglow_evening');const prompt=await c.getPrompt({name:'plan_an_afterglow_evening',arguments:{}});const text=prompt.messages[0].content.text;assert.match(text,/afterglow_status/);assert.match(text,/ambigu/);assert.match(text,/Never switch/);assert.match(text,/no reservations/);}finally{await c.close();}});
async function httpFixture(options={}){const server=http.createServer(createMcpHttpHandler(options));await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=new URL(`http://127.0.0.1:${server.address().port}/api/mcp`);const c=new Client({name:'fixture-http-client',version:'1.0.0'});await c.connect(new StreamableHTTPClientTransport(url));return{c,url,close:async()=>{await c.close();await new Promise(r=>server.close(r));}};}
test('Streamable HTTP MCP performs initialization and sample tool calls',async()=>{const h=await httpFixture({env:{}});try{const tools=await h.c.listTools();assert.equal(tools.tools.length,4);const p=parse(await h.c.callTool({name:'afterglow_plan_evening',arguments:sample}));assert.equal(p.stops.length,3);}finally{await h.close();}});
test('HTTP MCP live fixture traverses real tool handler and Qloo contracts',async()=>{const calls=[];const ids=['00000000-0000-0000-0000-000000000001','00000000-0000-0000-0000-000000000002'];const client={request:async(op,params)=>{calls.push({op,params});return [1,2,3].map(i=>({entity_id:`10000000-0000-0000-0000-00000000000${i}`,name:`Fixture ${i}`,query:{affinity:.5}}));}};const h=await httpFixture({env:{QLOO_ENABLED:'true',QLOO_API_KEY:'fixture-not-a-credential'},client});try{const p=parse(await h.c.callTool({name:'afterglow_plan_evening',arguments:{...sample,mode:'live',people:ids.map(id=>[id])}}));assert.equal(p.mode,'live');assert.equal(calls.length,2);assert.equal(p.cost,null);assert.deepEqual(p.stops[0].qlooRanks,[1,1]);assert.deepEqual(p.stops[0].qlooAffinity,[.5,.5]);}finally{await h.close();}});
test('HTTP MCP rejects hostile origins and hosts before tool execution',async()=>{const h=await httpFixture({env:{}});try{const payload={jsonrpc:'2.0',id:1,method:'tools/list',params:{}};for(const headers of [{origin:'https://evil.example'},{host:'evil.example'},{'sec-fetch-site':'cross-site'}]){const status=await new Promise((resolve,reject)=>{const req=http.request(h.url,{method:'POST',headers:{'content-type':'application/json',...headers}},res=>{res.resume();res.on('end',()=>resolve(res.statusCode));});req.on('error',reject);req.end(JSON.stringify(payload));});assert.equal(status,403,JSON.stringify(headers));}const oversized=await fetch(h.url,{method:'POST',headers:{'content-type':'application/json'},body:'x'.repeat(13000)});assert.equal(oversized.status,413);}finally{await h.close();}});
