import test from 'node:test';import assert from 'node:assert/strict';import{readFile}from'node:fs/promises';import{JSDOM}from'jsdom';import{buildSamplePlan}from'../lib/planner.mjs';import{tastes,vibes}from'../public/catalog.js';
const html=await readFile(new URL('../public/index.html',import.meta.url),'utf8'),script=(await readFile(new URL('../public/app.js',import.meta.url),'utf8')).replace("import {tastes,vibes} from './catalog.js';",'');
const wait=()=>new Promise(r=>setTimeout(r,15));
function setup(){const dom=new JSDOM(html,{url:'http://localhost:4177',runScripts:'outside-only'}),w=dom.window;w.tastes=tastes;w.vibes=vibes;w.structuredClone=structuredClone;w.AbortController=AbortController;w.HTMLElement.prototype.scrollIntoView=()=>{};w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};w.fetch=async(url,opts)=>{if(url==='/api/status')return{ok:true,json:async()=>({enabled:false})};try{return{ok:true,json:async()=>buildSamplePlan(JSON.parse(opts.body))};}catch(e){return{ok:false,json:async()=>({error:e.message})};}};w.eval(script);return {dom,w,doc:w.document,click:s=>w.document.querySelector(s).click()};}
test('UI initial rendering, honest mode disclosure and missing integration',async()=>{const {w,doc,click}=setup();await wait();assert.equal(doc.querySelectorAll('.stop-card').length,3);assert.match(doc.querySelector('#sample-note').textContent,/fictional/);click('#source-button');assert.ok(doc.querySelector('#about-dialog').open);assert.equal(doc.querySelector('#use-live').disabled,true);assert.match(doc.querySelector('#connection-status').textContent,/not connected/);w.close();});
test('UI add/remove, save/open, swap and save revision flows',async()=>{const {w,doc,click}=setup();await wait();click('.add-taste');click('[data-taste="nature"]');assert.match(doc.querySelector('#tastes-a').textContent,/Mary Oliver/);click('#taste-dialog .close-dialog');click('[data-remove="nature"]');assert.doesNotMatch(doc.querySelector('#tastes-a').textContent,/Mary Oliver/);click('#save-plan');click('#saved-tab');assert.equal(doc.querySelectorAll('.saved-card').length,1);click('[data-open]');const old=doc.querySelector('.stop-card h4').textContent;click('[data-swap="0"]');click('.alternative');assert.notEqual(doc.querySelector('.stop-card h4').textContent,old);const changed=doc.querySelector('.stop-card h4').textContent;click('#save-plan');click('#saved-tab');click('[data-open]');assert.equal(doc.querySelector('.stop-card h4').textContent,changed);assert.equal(JSON.parse(w.localStorage.getItem('afterglow.saved.v1')).length,1);w.close();});
test('UI cannot select more than five tastes',async()=>{const {w,doc,click}=setup();await wait();click('.add-taste');click('[data-taste="nature"]');click('[data-taste="pop"]');click('[data-taste="food"]');assert.equal(doc.querySelector('#count-a').textContent,'5 / 5');assert.match(doc.querySelector('#toast').textContent,/Five/);w.close();});
test('UI invalid profile displays error and preserves old itinerary',async()=>{const {w,doc,click}=setup();await wait();const before=doc.querySelector('.result-title').textContent;while(doc.querySelector('#tastes-a button'))doc.querySelector('#tastes-a button').click();doc.querySelector('#date-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await wait();assert.equal(doc.querySelector('#form-error').classList.contains('hidden'),false);assert.match(doc.querySelector('#form-error').textContent,/one and five/);assert.equal(doc.querySelector('.result-title').textContent,before);assert.equal(doc.querySelector('#generate').disabled,false);w.close();});
test('UI $50 budget submission and no fabricated cost overrun',async()=>{const {w,doc}=setup();await wait();doc.querySelector('#budget').value='50';doc.querySelector('#budget').dispatchEvent(new w.Event('input'));doc.querySelector('#date-form').dispatchEvent(new w.Event('submit',{cancelable:true}));await wait();assert.equal(doc.querySelector('#budget-value').textContent,'$50');assert.ok(Number(doc.querySelector('.budget-summary strong').textContent.slice(1))<=50);w.close();});
test('UI save removal exposes empty state',async()=>{const {w,doc,click}=setup();await wait();click('#save-plan');click('#saved-tab');click('[data-delete]');assert.equal(doc.querySelectorAll('.saved-card').length,0);assert.ok(doc.querySelector('.empty-saved'));assert.equal(w.localStorage.getItem('afterglow.saved.v1'),'[]');w.close();});
test('UI original plan explanations do not change with unsent form edits',async()=>{const {w,doc,click}=setup();await wait();const before=doc.querySelector('.why-box').textContent;while(doc.querySelector('#tastes-a button'))doc.querySelector('#tastes-a button').click();click('#save-plan');assert.equal(doc.querySelector('.why-box').textContent,before);w.close();});
test('untrusted display content is escaped in place cards',async()=>{const {w,doc,click}=setup();await wait();click('#save-plan');const saved=JSON.parse(w.localStorage.getItem('afterglow.saved.v1'));saved[0].title='<img src=x onerror=alert(1)>';w.localStorage.setItem('afterglow.saved.v1',JSON.stringify(saved));w.eval(script);await wait();click('#saved-tab');assert.equal(doc.querySelectorAll('#saved-list img').length,0);assert.match(doc.querySelector('#saved-list').textContent,/<img/);w.close();});
